### ISSUE TITLE
LeanMapper support

### ISSUE THREAD

**Issue by JanGalek** [ublaboo/datagrid#535]
## Czech
Zdravím,
bylo by možné přidat podporu pro LeanMapper ? Vše mi sice fungovalo jak to je, až na big inline edit, kde se tlačítko pro editaci skrylo a nic víc se nestalo. Poté jsem přepnul na dibi a fungovalo v pořádku, takže v nastavení gridu by problém být neměl.

Díky

## English
Hi,
I want ask you, if is possible add support for LeanMapper ? Everything worked ok, but big inline edit is problematic, edit button hided and nothing did. I try dibi and everything work allright, than problem with setting grid doesnt.

Thank

**Comment by paveljanda** [comment]
@JanGalek Problem is, there is no official fluent interface imlementation for leanmapper. Or is there? If I'm not mistaken, there where some unofficial experiments (LeanMapperQuery, QueryObject, ...), but I won't support them because the are not officially supported and developed. Haha, nor is the LeanMapper itself. :D

**Comment by JanGalek** [comment]
@paveljanda oh ok. So do you know some mapper whitch support firebird database and whitch will work with datagrid ? I look for some, but not success.

**Comment by paveljanda** [comment]
@JanGalek Cool. Closing this issue now. :)
