### ISSUE TITLE
RFC: DataGrid::setDataSource (is in fact factory)

### ISSUE THREAD

**Issue by Achse** [ublaboo/datagrid#80]
I'd like to discuss this befeore I start writing pull request.

**Problem**:
* method says that sets DataSouce to the grid.
* but in fact does much more.

It works like adapter between "some data / data providers with unknown structure" and `IDataSource`.

This has those effects:
* method is misleading and with lack of annotation causes unnecessary warnigns.
![xxxx](https://cloud.githubusercontent.com/assets/383295/12948453/9c1ee0fa-d002-11e5-964a-826d8b45ae6d.png)
* you have to add `instanceof` / `is_type` / `is_xyz` elseif anytime you add another DataSource into the package

**Possible solutions**:
1. Add proper annotation for the method and maintain it, adding it with every DataSource added. (This is easy but does not solve the core of the problem, but one smysptom of it.) And also:
```php
/**
* @param DataSource\IDataSource|array|\DibiFluent|QueryBuilder|Selection|WhatteverDbLayerData|AnotherDataPromise $source
```
is little bit ugly.
2. Remove adapter logic from the method and lay responsibility of creating DataSource object to another class (mostly component of presenter / where datagrid object is factored). (This is nice and clean but makes it harder to user, user of Grid need to write more code).

**My opinion**
I think that adapter logic exceed the responsibility that setter should have. User of datagrid should know what is sending into it and there is no need for this logic.

I am ok with code like this:
```php
$queryBuilder = $this->queryBuilderProvider->getQueryBuilder();
$grid->setDataSource(new DoctrineDataSource($queryBuilder, 'id'));
```

Alternatively I suggest to implement all methods like:
* `setDoctrineDataSource`
*  `setDibiFluentDataSouce`
* ....

Which solves the problem of autowiring `$this->primary_key` into DataSource and also keeps API of `DataSource` easy to use.

----

What do you think, what would be better?

**Comment by paveljanda** [comment]
That method really became a weird and confusing factory.

What led to that problem is the fact that there is a datasource*1 and a datasource*2. The first one is the one given by user (DibiFluent, QB, ...) and the second one is a native class that provides datagrid "adapter" betweeen datasource*1 (DibiFluent, QB, ...) and datagrid itself.

I still want to let the datagrid decide, what datasource*2 will it choose. It much more simple for the user. Especially when he's not so much experienced.

There is in fact a third class (...) - `DataModel`, which just encloses datasource*2 and talks to datagrid.

Maybe, `DataModel` was intended to provide that datasoruce*1 resolution.

My opinion is, simply move the `setDataSource()` method to `DataModel` and name it more conveniently. Maybe add some exceptions throwing - when user tries to set `DataGrid` datasource like you did for the first time, it should say how to set it properly.

What do you think about my solution? It does not entirely solves the problem of two datasources, but cleans think up a bit.

**Comment by Achse** [comment]
I am fan of static types and most specific type check as possible. I know .. I should chose Java instead of PHP at all, but its story for another day :D

For me as user is important clean API. How is this adapter written is little bit irrelevant for me. In my opinion, there should be no adapter at all, but I understand argument of simplicity. 

* If you want to persist method with API `setDataSource(mixed $dataSource*1)`. All I ask is proper annotation for type checking.

**Comment by paveljanda** [comment]
I moved the "DataSrouce factory" to the `DataModel` class, which makes more sense to me and does not require so many changes in code.

Does that seem at least a bit better to you? (Checkout master branch)
